# should be in .circleci folder
orbs:
  aws-cli: circleci/aws-cli@3.1.3
commands:
  login-ecr:
    steps:
      -run:
        name: Login to ECR
        command: just login ${AWS_ECR_DOMAIN}
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - aws-cli/install
      - run:
          name: Install Just CLI - latest
          command: |
            curl \
              -- proto '=https' \
              -- tlsv1.2 -sSf https://just.systems/install.sh \
              | bash -s -- --to /tmp/just
      - setup_remote_docker:
        docker_layer_caching: true
        version: 20.10.17
      - checkout
      - login-ecr
      - run:
          name: Build images
          ## template engine example here
          command: just build "my-name"
      - run:
          name: Push images
          ## template engine example here
          command: just push "my-name"
  refresh:
    docker:
      - image: $AWS_ECR_DOMAIN/my-name:${CIRCLE_SHA1}
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_access_secret_key: $AWS_ACCESS_SECRET_KEY
    resource_class: small
    working_directory: /usr/src/app
    steps:
      - run:
        name: Refresh stack
        command: just refresh "my-name"
  preview:
    docker:
      - image: $AWS_ECR_DOMAIN/my-name:${CIRCLE_SHA1}
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_access_secret_key: $AWS_ACCESS_SECRET_KEY
    resource_class: small
    working_directory: /usr/src/app
    steps:
      - run:
        name: Refresh stack
        command: just refresh "my-name"
  update:
    docker:
      - image: $AWS_ECR_DOMAIN/my-name:${CIRCLE_SHA1}
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_access_secret_key: $AWS_ACCESS_SECRET_KEY
    resource_class: small
    working_directory: /usr/src/app
    steps:
      - run:
        name: Update stack
        command: just update "my-name"
  workflows:
    build-preview-update:
      jobs:
        - build:
            context:
              - albibenni-aws
        - refresh:
            context:
              - albibenni-aws
            requires:
              - build
        - preview:
            context:
              - albibenni-aws
            requires:
              - refresh
        - update:
            context:
              - albibenni-aws
            requires:
              - preview
